name: Integração Contínua (Build, Lint, Tests)

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build-e-testes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Instalar o uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true # Faz cache das dependências para rodar ainda mais rápido

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Criar ambiente virtual e instalar dependências (Build)
      run: |
        # Cria o ambiente virtual na pasta .venv
        uv venv .venv

        # Instala as dependências lendo o requirements.txt usando o uv
        uv pip install -r requirements.txt

        # Adiciona o .venv ao PATH global do GitHub Actions
        echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH

    - name: Análise Estática com Ruff (Lint)
      run: |
        # Falha o pipeline se encontrar erros de sintaxe ou más práticas
        ruff check src/ tests/

    - name: Testes Automatizados e Cobertura
      run: |
        # Roda o pytest e exibe a porcentagem de código testado no log
        pytest --cov=src --cov-report=term
